apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-operator

resources:
- namespace.yaml
- deploy.yaml

configMapGenerator:
- name: kubeconfig-file
  files:
  - config
- name: tekton-operator-env-vars
  literals:
    - key=value
